post_install() {
	if [ -z "$(grep "gi\.require_version('Vte', '2.90')" /usr/share/virt-manager/virtManager/serialcon.py)" ]; then
		sed -i "s/^\(from gi\.repository import Vte\)$/import gi\n\
gi\.require_version('Vte', '2.90')\n\
\1/g" /usr/share/virt-manager/virtManager/serialcon.py 
	fi
}

pre_upgrade() {
	post_remove
}

post_upgrade() {
	post_install
}

post_remove() {
	sed -i "/import gi/d" /usr/share/virt-manager/virtManager/serialcon.py
	sed -i "/gi\.require_version('Vte', '2.90')/d" /usr/share/virt-manager/virtManager/serialcon.py 
}
